<a href="https://colab.research.google.com/github/aye21874/AML_Final_Project/blob/main/project_aml_timefeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install kaggle
# !mkdir ~/.kaggle
# !cp kaggle.json ~/.kaggle/
# !chmod 600 ~/.kaggle/kaggle.json
# !kaggle competitions download h-and-m-personalized-fashion-recommendations -f transactions_train.csv
# !unzip transactions_train.csv.zip

Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.10.8)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.1)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
f = 'transactions_train.csv'
df = pd.read_csv(f)

In [ ]:
from datetime import datetime
import calendar

def to_date(dt):
    dat = datetime.strptime(dt, '%Y-%m-%d')
#     print(dat)
    return calendar.day_name[dat.weekday()]

def to_season(dt):
    dat = datetime.strptime(dt, '%Y-%m-%d')
    month = dat.month
    if(month < 3):
        return 'Winter'
    elif(month < 6):
        return 'Spring'
    elif(month < 9):
        return 'Summer'
    elif(month < 12):
        return 'Fall'
    else:
        return 'Winter'
    print(dat.month)
to_date('2018-09-20')
to_season('2018-09-20')

# my_date = date.today()
# calendar.day_name[my_date.weekday()]  #'Wednesday'

'Fall'

In [ ]:
actualpd = df

In [ ]:
actualpd['weekday'] = actualpd['t_dat'].apply(to_date)
actualpd['Season'] = actualpd['t_dat'].apply(to_season)
most_common = actualpd.groupby(['customer_id']).agg(lambda x:x.value_counts().index[0])

In [ ]:
most_common

,t_dat,article_id,price,sales_channel_id,weekday,Season
customer_id,,,,,,
00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d25f88aa139fdfc657,2020-03-21,568601006,0.050831,2,Saturday,Spring
0000423b00ade91418cceaf3b26c6af3dd342b51fd051eec9c12fb36984420fa,2020-04-22,811835004,0.016932,2,Tuesday,Spring
000058a12d5b43e67d225668fa1f8d618c13dc232df0cad8ffe7ad4a1091e318,2020-04-18,663713001,0.025407,2,Saturday,Spring
00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2c5feb1ca5dff07c43e,2019-06-09,742079001,0.030492,2,Sunday,Summer
00006413d8573cd20ed7128e53b7b13819fe5cfc2d801fe7fc0f26dd8d65a85a,2020-08-12,399061015,0.027102,2,Wednesday,Summer
...,...,...,...,...,...,...
ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e4747568cac33e8c541831,2019-04-03,712924008,0.016932,2,Wednesday,Spring
ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab53481233731b5c4f8b7,2019-04-29,699623004,0.016932,2,Monday,Spring
ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a1778d0116cffd259264,2019-01-24,484398001,0.025407,2,Thursday,Winter
ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38b2236865d949d4df6a,2020-04-05,866755002,0.016932,2,Sunday,Spring
ffffd9ac14e89946416d80e791d064701994755c3ab686a1eaf3458c36f52241,2019-12-04,806050001,0.084729,2,Wednesday,Winter

In [ ]:
time_most_common = most_common[['weekday', 'Season']]
time_most_common

                                                      weekday  Season
customer_id
00000dbacae5abe5e23885899a1fa44253a17956c6d1c3d...   Saturday  Spring
0000423b00ade91418cceaf3b26c6af3dd342b51fd051ee...    Tuesday  Spring
000058a12d5b43e67d225668fa1f8d618c13dc232df0cad...   Saturday  Spring
00005ca1c9ed5f5146b52ac8639a40ca9d57aeff4d1bd2c...     Sunday  Summer
00006413d8573cd20ed7128e53b7b13819fe5cfc2d801fe...  Wednesday  Summer
...                                                       ...     ...
ffffbbf78b6eaac697a8a5dfbfd2bfa8113ee5b403e4747...  Wednesday  Spring
ffffcd5046a6143d29a04fb8c424ce494a76e5cdf4fab53...     Monday  Spring
ffffcf35913a0bee60e8741cb2b4e78b8a98ee5ff2e6a17...   Thursday  Winter
ffffd7744cebcf3aca44ae7049d2a94b87074c3d4ffe38b...     Sunday  Spring
ffffd9ac14e89946416d80e791d064701994755c3ab686a...  Wednesday  Winter

[1362281 rows x 2 columns]

In [ ]:
time_most_common.to_csv('customer_id.csv')